### ISSUE TITLE
Unknown expected types for SVGFigure parameters

### ISSUE THREAD

**Issue by effigies** [btel/svg_utils#57] opened 2021-01-05 17:32 UTC
The recently released 0.3.2 has resulted in the following (truncated) traceback:

```Python
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/viz/utils.py", line 360, in compose_view
    fig = SVGFigure(width, heights[:nsvgs].sum())
  File "/usr/local/miniconda/lib/python3.7/site-packages/svgutils/transform.py", line 242, in __init__
    self._width = width.value
AttributeError: 'numpy.int64' object has no attribute 'value'
```

Looking at the [docs for SVGFigure](https://svgutils.readthedocs.io/en/latest/transform.html#svgutils.transform.SVGFigure), a numeric value seems appropriate. I'm not sure what sort of object with a `.value` attribute is expected to fix our invocation, so currently I'm pinning 0.3.1.

Issue introduced in #27.

**Comment by btel** [comment] 2021-01-07 09:08
thanks for reporting, I am looking into it

**Comment by hartwork** [comment] 2021-01-10 18:12
@effigies here's [how I addressed the same issue using `Unit`](https://github.com/hartwork/xiangqi-setup/commit/9d5ef64274ee9873351ac6b0d91ee0ec83bce635).

**Comment by btel** [comment] 2021-01-10 22:10
@effigies I just merged the PR #58  that should solve the issue. Can you test it with your code? If the problem is fixed, I will make another release.

**Comment by mgxd** [comment] 2021-01-11 16:56
@btel I can confirm #58 fixes the problem - thanks!

**Comment by effigies** [comment] 2021-01-11 19:06
Thanks, @mgxd. @btel to be clear, he's working on the same project that I am.

**Closed** 2021-02-10 21:26 UTC
